# Generated by Django 4.0.5 on 2022-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_city_product_purveyor_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=50)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
